# Retourne la liste des directeurs des films Harry Potter

PREFIX schema: <https://schema.org/>
PREFIX thing: <https://schema.org/Thing/>
PREFIX movie: <https://schema.org/Movie/>

SELECT DISTINCT ?Director_URI ?Director_Name
WHERE {
  ?Film_URI movie:director ?Director_URI .

  ?Director_URI thing:name ?Director_Name .

  ?Film_URI thing:name ?Film_Title .
  FILTER(CONTAINS(?Film_Title, "Harry Potter"))
}
