# Recherche de films dont le titre contient "harry potter"

SELECT ?Film_URI ?Titre
WHERE {
  ?Film_URI a <http://schema.org/Movie> .
  ?Film_URI <http://schema.org/name> ?Titre .
  FILTER(CONTAINS(LCASE(?Titre), "harry potter"))
}