# Tri des films par date de sortie décroissante

SELECT ?Film_URI ?Titre ?Date_de_sortie
WHERE {
  ?Film_URI a <http://schema.org/Movie> .
  ?Film_URI <http://schema.org/name> ?Titre .
  ?Film_URI <http://schema.org/releaseDate> ?Date_de_sortie .
}
ORDER BY DESC((?Date_de_sortie))